### ISSUE TITLE
Does it work on q662?

### ISSUE THREAD

**Issue by csdvrx** [Atom-X-Devs/android_kernel_sdm660_linux_stable#1]
Will it work on a Qualcomm BengalP (Snapdragon 662?)

I'm not sure about the SDM or the Board ID (MSM) from a running kernel.

I have access to the dmesg and /proc/config.gz

**Comment by csdvrx** [comment]
It's an Onyx Boox, and given cat /proc/cpuinfo | tail -n1 :

```
BOOX:/ # cat /proc/cpuinfo  |tail -n 1
Hardware        : Qualcomm Technologies, Inc BENGALP-IOT
```

I think it may be a using bengalp-iot.dtsi ( https://android.googlesource.com/kernel/msm-extra/devicetree/+/refs/heads/android-msm-barbet-4.19-s-qpr3-beta-2/qcom/bengalp-iot.dtsi )

It may not be a problem to compile modules for filesystem, but I would like eventually to compile and kexec a kernel.

**Comment by Tashar02** [comment]
It is usable.
You can merge the latest `LA.UM.9.15.1.r1-07200-KAMORTA.0` bengal tag and proceed to use the base or just use the base without it. Though I recommend merging it beforehand on top of the current source.
Use the above mentioned tag to import your wifi drivers, audio-kernel etc.

**Comment by csdvrx** [comment]
Thanks a lot, I will try and report back the results of trying insmod and then kexec
